name: C/C++ CI

on:
  push:
    branches: [ my_dwm ]
    tags: 
      - 'v*'
  pull_request:
    branches: [ my_dwm ]
    tags: 
      - 'v*'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: make
      run: make
